### ISSUE TITLE
Modules management tab is empty

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr5#20]
In the configuration form, there are 3 tabs, the third one is for the modules. This one is empty.
Also, there is a dedicated form to manage the modules.

Either remove the empty tab, either move module management in it and remove the module management form.

![image](https://user-images.githubusercontent.com/17324443/147464760-83e29ac5-9215-4bc9-9c78-72d58e662e28.png)

**Comment by deurk** [comment]
It's not part of the system but part of the core of FoundryVTT and that is where modules that have configuration options will display them. In your example, it's empty because you have no module allowing configuration but if you install Dice So Nice for example, you will see the tab populated with options.
